name: Release
on:
  push:
    branches:
      - master
  schedule:
    - cron: 30 6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - "https://nixos.org/channels/nixos-19.09"
          - "https://nixos.org/channels/nixos-unstable"
          - "https://nixos.org/channels/nixpkgs-unstable"
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v3
      - run: nix-channel --add ${{ matrix.channel }} nixpkgs
      - run: nix-channel --update
      - run: nix eval -f default.nix 'lib'
      - run: nix eval -f default.nix 'modules'
      - run: nix eval -f default.nix 'overlays'
      - uses: cachix/cachix-action@v2
        with:
          name: knopki-nixexprs
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          file: ci.nix
          attributes: cacheOutputs
      # - run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"
