name: "Check for updates"
on:
  schedule:
    - cron: "57 7 * * *"
jobs:
  list-packages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Setup cachix
        uses: cachix/cachix-action@v6
        with:
          name: jeremiehuchet
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: Cache build dependencies
        run: |
          nix-shell .github/auto-pr/shell.nix --run true
          nix-store -qR --include-outputs $(nix-instantiate .github/auto-pr/shell.nix) | cachix push jeremiehuchet
      - id: set-matrix
        name: Find packages
        run: |
          find pkgs -type f -name github.json  -printf '{"path": "%h", "type": "github"},' > packages_list
          find pkgs -type f -name package.json -printf '{"path": "%h", "type": "node2nix"},' >> packages_list
          echo "::set-output name=matrix::{ include: [ $(cat packages_list) ] }"
  check-updates:
    needs: list-packages
    strategy:
      matrix: "${{fromJson(needs.list-packages.outputs.matrix)}}"
      fail-fast: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    name: ${{matrix.path}} (${{matrix.type}})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Setup cachix
        uses: cachix/cachix-action@v6
        with:
          name: jeremiehuchet
      - name: github update check
        if: ${{ matrix.type == 'github' }}
        run: nix-shell .github/auto-pr/shell.nix --run "./.github/auto-pr/update-github-package.sh ${{ matrix.path }}"
      - name: node2nix update check
        if: ${{ matrix.type == 'node2nix' }}
        run: nix-shell .github/auto-pr/shell.nix --run "./.github/auto-pr/update-node2nix-package.sh ${{ matrix.path }}"
      - name: open pull request
        run: nix-shell .github/auto-pr/shell.nix --run "./.github/auto-pr/submit-pull-request.sh ${{ matrix.path }}"
